/* Published Homex journal snapshot. These records match the six live Selldone
   articles and avoid rate-limited public reads on every page visit. */
export const HOMEX_JOURNAL = [
  {
    id: 744767, blogId: 31880, category: { id: 8627, name: "Decor Styling", count: 1 }, title: "Mixing Decor Without Visual Clutter", slug: "mixing-decor-without-visual-clutter", description: "Build a calm decorative composition with repetition, scale, and breathing room.", image: "https://cdn.selldone.com/app/shops/15574/blog-categories/photojpg970cd2047917693fd3c29b9505afda34128.jpg", date: "2026-08-19T15:29:17Z",
    body: `<p>Variety feels intentional when a few elements repeat. Choose two or three materials, such as warm wood, ceramic, and woven fibre, then let them appear in different parts of the room. A restrained colour family gives artwork, books, and collected objects enough freedom without making every surface compete.</p><p>Vary scale rather than lining up many small pieces. One tall vase, a medium bowl, and a low stack of books create a clearer silhouette than a row of equal objects. Leave empty space around each group so the eye can pause. Editing is part of styling: rotate favourite pieces seasonally instead of displaying everything at once.</p>`,
  },
  {
    id: 744766, blogId: 31879, category: { id: 8626, name: "Home Office", count: 1 }, title: "Create a Healthier Home Office", slug: "create-a-healthier-home-office", description: "Improve posture and focus with thoughtful desk, chair, and lighting choices.", image: "https://cdn.selldone.com/app/shops/15574/blog-categories/photojpg9d5b0847e4d9a6f832b066d8fdfb3270128.jpg", date: "2026-08-19T15:29:14Z",
    body: `<p>A healthier workspace begins with adjustability. Set the chair so feet rest flat, knees stay near a right angle, and the lower back feels supported. The desk should let shoulders relax while typing. Raise the screen until its top sits around eye level, reducing the urge to lean forward.</p><p>Place the desk near daylight without facing strong glare, then add a focused lamp for evening work. Keep frequently used items within easy reach and leave one clear surface for thinking. Short movement breaks matter as much as furniture: stand, stretch, and change focus regularly. Comfort supports concentration when the room encourages small, healthy shifts.</p>`,
  },
  {
    id: 744765, blogId: 31878, category: { id: 8625, name: "Living Room Ideas", count: 1 }, title: "A Coffee Table That Works Harder", slug: "a-coffee-table-that-works-harder", description: "Choose a coffee table with the right proportions, storage, and everyday function.", image: "https://cdn.selldone.com/app/shops/15574/blog-categories/photojpgecd715f1b75e98235be5c6599d3ed471128.jpg", date: "2026-08-19T15:29:11Z",
    body: `<p>The best coffee table supports the way a room is actually used. Its top should sit close to sofa-seat height, and the length usually feels balanced at about two-thirds of the sofa. Leave enough space to walk around it without turning every trip across the room into an obstacle course.</p><p>Storage shelves suit busy households, nesting tables adapt to guests, and rounded corners are kinder in compact rooms. Consider the material too: sealed wood is forgiving, glass keeps a room visually light, and stone adds weight and texture. A useful table combines proportion, reach, and maintenance with a shape that complements nearby seating.</p>`,
  },
  {
    id: 744764, blogId: 31877, category: { id: 8624, name: "Rug Guides", count: 1 }, title: "Finding the Perfect Rug Size", slug: "finding-the-perfect-rug-size", description: "Simple rug-sizing rules for living rooms, bedrooms, and dining spaces.", image: "https://cdn.selldone.com/app/shops/15574/blog-categories/photojpg28ee8582f8a22df5c01d697f1dce0642128.jpg", date: "2026-08-19T15:29:09Z",
    body: `<p>A rug should connect furniture rather than float between it. In a living room, place at least the front legs of the sofa and chairs on the rug. Larger rooms often feel calmer when every seating leg sits inside the border. Leave a consistent strip of visible floor around the edges.</p><p>For dining spaces, add roughly sixty centimetres beyond the tabletop on every side so chairs remain on the rug when pulled out. In bedrooms, choose a rug wide enough to extend beyond the bed or use two generous runners. Always mark dimensions with tape before ordering; scale is easier to judge on the floor.</p>`,
  },
  {
    id: 744763, blogId: 31876, category: { id: 8623, name: "Lighting Ideas", count: 1 }, title: "Layering Light for a Warmer Home", slug: "layering-light-for-a-warmer-home", description: "Use ambient, task, and accent lighting to create flexible and inviting rooms.", image: "https://cdn.selldone.com/app/shops/15574/blog-categories/photojpgc0580b69a916761a6f5b8474774813e6128.jpg", date: "2026-08-19T15:29:06Z",
    body: `<p>A welcoming room rarely depends on one ceiling fixture. Begin with soft ambient light that fills the space, then add task lighting beside a sofa, desk, or reading chair. Finally, use a small accent lamp to reveal artwork, texture, or a quiet corner. Each layer should solve a different need.</p><p>Warm bulbs around 2700K make wood and natural fabrics feel richer. Keep shade materials consistent enough to create rhythm, but vary lamp height to avoid a flat effect. Dimmers are especially useful in living and dining rooms, allowing the same furniture arrangement to shift from practical daytime use to relaxed evening atmosphere.</p>`,
  },
  {
    id: 744762, blogId: 31875, category: { id: 8622, name: "Dining Guides", count: 1 }, title: "How to Choose the Right Dining Table", slug: "choose-the-right-dining-table", description: "A practical guide to selecting a dining table that fits your room, routine, and style.", image: "https://cdn.selldone.com/app/shops/15574/blog-categories/photojpg44d80b50cd65e0117dbb72e4a6fb8233128.jpg", date: "2026-08-19T15:29:03Z",
    body: `<p>Start with the room, not the table. Leave at least ninety centimetres around every side so chairs can move comfortably and people can pass behind them. A rectangular table suits long rooms, while round shapes soften compact spaces and make conversation easier. Measure doors and stairways before choosing an extendable design.</p><p>Think about daily life next. Solid wood develops character, veneer offers visual consistency, and stone needs more care around spills. Choose a size for ordinary meals, then use leaves for guests. Comfortable dining comes from proportion, durable materials, and enough breathing room—not simply the largest table that fits.</p>`,
  },
];
